name: state_machine
version: 2.2.5
description: Finite state machine library. Easily define legal state transitions.
    Listen to state entrances, departures, and transitions.
homepage: https://github.com/Workiva/state_machine

environment:
    sdk: ">=2.11.0 <3.0.0"

dependencies:
    w_common: ^1.20.1

dev_dependencies:
    build_runner: '>=1.7.1 <3.0.0'
    build_test: ">=0.10.9 <2.0.0"
    build_web_compilers: ^2.5.1
    dart_dev: ^3.0.0
    dart_style: ^1.3.1
    test: ^1.15.7
