name: state_machine
version: 2.0.4
description: Finite state machine library. Easily define legal state transitions. Listen to state entrances, departures, and transitions.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/state_machine

environment:
  sdk: '>=1.24.3<3.0.0'

dependencies:
  w_common: ^1.15.0

dev_dependencies:
  build_runner: ">=0.6.0 <1.0.0"
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ">=0.2.0 <1.0.0"
  coverage: ">=0.10.0 <0.13.0"
  dart_dev: ^2.0.0
  dart_style: ^1.0.0
  test: ">=0.12.30 <2.0.0"
